### PR TITLE
[imporvement] load adpater need user specify the adapter path

### PR DESCRIPTION
**Pull request by yezhem**
* init context by config

### CODE REVIEW

**Review by waitfor-night — APPROVED** [review]

**Review by waitfor-night — APPROVED** [review]

**Review by waitfor-night — APPROVED** [review]
OK

**Comment by mikecovlee** [comment]
这种情况下，写死了是从路径中读取，未来如何扩展从其它来源，如hugging face hub上下载？

**Comment by yezhem** [comment]
> 这种情况下，写死了是从路径中读取，未来如何扩展从其它来源，如hugging face hub上下载？

if you do not specify the LoRA adapter's path, dpo can not use the same adapter but a different adapter name.
add repo argument to specify the adapter should be downloaded to the path.
should add the function to __init_weight function in the feature if you need it.

**Comment by yezhem** [comment]
this commit is append to #214 so close this one.

**Pull request closed without merging**
